app = "windows-tcg"
primary_region = "nrt"


[env]
VERSION = "11"
RAM_SIZE = "131072"
CPU_CORES = "16"
STORAGE_SIZE = "500G"

[[mounts]]
source = "windows"
destination = "/storage"

[[services]]
protocol = "tcp"
internal_port = 8006
auto_start_machines = true
auto_stop_machines = false

[[services.ports]]
port = 8006
handlers = ["https"]

[[services.ports]]
port = 443
handlers = ["tls", "https"]

[[services]]
protocol = 3389
internal_port = 3389
auto_start_machines = true
auto_stop_machines = false

[[services.ports]]
port = 3389

[vm]
cpu_kind = "performance"
cpus = "1"
memory = "500gb"
memory_mb = "2048"
