app = 'korean-laptop-lounge-bot'
primary_region = 'nrt'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 8006
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['windows']

[processes]
  windows = ''

[[vm]]
  memory = '8192'
  cpu_kind = 'performance'
  cpus = 4

[[services]]
  protocol = 'tcp'
  internal_port = 3389
  ports = [3389]

[[services]]
  protocol = 'udp'
  internal_port = 3389
  ports = [3389]

[env]
  VERSION = '11'
  LANGUAGE = 'korean'
  RAM_SIZE = '4G'
  CPU_CORES = '2'
  DISK_SIZE = '64G'
